[build]
	command = "pnpm build"
	publish = "_site"
[[plugins]]
	package = "@netlify/plugin-sitemap"

	[plugins.inputs]
		exclude = [
			'./admin',
			'./admin/index.html',
			'./blog',
			'./reports/lighthouse.html',
		]
