[build]
  publish = "_site"
  command = "npm run build"
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  exclude = [
    './admin/index.html',
    './admin',
    './blog',
    './reports/lighthouse.html',
  ]
[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = 'reports/lighthouse.html'